# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1298, 839)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 921, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_FlowReport = QtWidgets.QWidget()
        self.tab_FlowReport.setObjectName("tab_FlowReport")
        self.pushButton_Save = QtWidgets.QPushButton(self.tab_FlowReport)
        self.pushButton_Save.setGeometry(QtCore.QRect(240, 660, 101, 28))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_SaveAs = QtWidgets.QPushButton(self.tab_FlowReport)
        self.pushButton_SaveAs.setGeometry(QtCore.QRect(490, 660, 101, 28))
        self.pushButton_SaveAs.setObjectName("pushButton_SaveAs")
        self.textEdit_report = QtWidgets.QTextEdit(self.tab_FlowReport)
        self.textEdit_report.setGeometry(QtCore.QRect(0, 0, 911, 641))
        self.textEdit_report.setObjectName("textEdit_report")
        self.tabWidget.addTab(self.tab_FlowReport, "")
        self.tab_SystemSketch = QtWidgets.QWidget()
        self.tab_SystemSketch.setObjectName("tab_SystemSketch")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.tab_SystemSketch)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 10, 891, 591))
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalSlider_zoom = QtWidgets.QSlider(self.tab_SystemSketch)
        self.horizontalSlider_zoom.setGeometry(QtCore.QRect(70, 630, 181, 22))
        self.horizontalSlider_zoom.setMaximum(200)
        self.horizontalSlider_zoom.setProperty("value", 150)
        self.horizontalSlider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_zoom.setObjectName("horizontalSlider_zoom")
        self.label_20 = QtWidgets.QLabel(self.tab_SystemSketch)
        self.label_20.setGeometry(QtCore.QRect(20, 630, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_RefreshSketch = QtWidgets.QPushButton(self.tab_SystemSketch)
        self.pushButton_RefreshSketch.setGeometry(QtCore.QRect(75, 664, 131, 28))
        self.pushButton_RefreshSketch.setObjectName("pushButton_RefreshSketch")
        self.groupBox = QtWidgets.QGroupBox(self.tab_SystemSketch)
        self.groupBox.setGeometry(QtCore.QRect(280, 630, 301, 51))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_Length = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Length.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.checkBox_Length.setObjectName("checkBox_Length")
        self.checkBox_DeltaP = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_DeltaP.setGeometry(QtCore.QRect(120, 20, 81, 20))
        self.checkBox_DeltaP.setObjectName("checkBox_DeltaP")
        self.checkBox_DeltaH = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_DeltaH.setGeometry(QtCore.QRect(220, 20, 81, 20))
        self.checkBox_DeltaH.setObjectName("checkBox_DeltaH")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_SystemSketch)
        self.groupBox_2.setGeometry(QtCore.QRect(600, 630, 301, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_Zvalue = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Zvalue.setGeometry(QtCore.QRect(30, 20, 81, 20))
        self.checkBox_Zvalue.setObjectName("checkBox_Zvalue")
        self.checkBox_Pressure = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Pressure.setGeometry(QtCore.QRect(130, 20, 81, 20))
        self.checkBox_Pressure.setObjectName("checkBox_Pressure")
        self.checkBox_Head = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Head.setGeometry(QtCore.QRect(230, 20, 81, 20))
        self.checkBox_Head.setObjectName("checkBox_Head")
        self.tabWidget.addTab(self.tab_SystemSketch, "")
        self.tab_SystemCurve = QtWidgets.QWidget()
        self.tab_SystemCurve.setObjectName("tab_SystemCurve")
        self.lineEdit_MinFlow = QtWidgets.QLineEdit(self.tab_SystemCurve)
        self.lineEdit_MinFlow.setGeometry(QtCore.QRect(120, 20, 121, 22))
        self.lineEdit_MinFlow.setObjectName("lineEdit_MinFlow")
        self.label_10 = QtWidgets.QLabel(self.tab_SystemCurve)
        self.label_10.setGeometry(QtCore.QRect(23, 23, 281, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_MaxFlow = QtWidgets.QLineEdit(self.tab_SystemCurve)
        self.lineEdit_MaxFlow.setGeometry(QtCore.QRect(430, 20, 121, 22))
        self.lineEdit_MaxFlow.setObjectName("lineEdit_MaxFlow")
        self.label_11 = QtWidgets.QLabel(self.tab_SystemCurve)
        self.label_11.setGeometry(QtCore.QRect(333, 23, 281, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_GenerateCurves = QtWidgets.QPushButton(self.tab_SystemCurve)
        self.pushButton_GenerateCurves.setGeometry(QtCore.QRect(660, 20, 191, 28))
        self.pushButton_GenerateCurves.setObjectName("pushButton_GenerateCurves")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_SystemCurve)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 911, 701))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.lineEdit_MinFlow.raise_()
        self.label_10.raise_()
        self.lineEdit_MaxFlow.raise_()
        self.label_11.raise_()
        self.pushButton_GenerateCurves.raise_()
        self.tabWidget.addTab(self.tab_SystemCurve, "")
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(1004, 780, 121, 31))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_GetFlowSystemFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_GetFlowSystemFile.setGeometry(QtCore.QRect(620, 22, 191, 28))
        self.pushButton_GetFlowSystemFile.setObjectName("pushButton_GetFlowSystemFile")
        self.textEdit_filepath = QtWidgets.QTextEdit(Dialog)
        self.textEdit_filepath.setGeometry(QtCore.QRect(10, 10, 591, 51))
        self.textEdit_filepath.setObjectName("textEdit_filepath")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(950, 90, 331, 681))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_ConstantFlowrateSource = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_ConstantFlowrateSource.setGeometry(QtCore.QRect(20, 30, 181, 20))
        self.radioButton_ConstantFlowrateSource.setObjectName("radioButton_ConstantFlowrateSource")
        self.lineEdit_SourceFlowrate = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_SourceFlowrate.setGeometry(QtCore.QRect(90, 70, 121, 22))
        self.lineEdit_SourceFlowrate.setObjectName("lineEdit_SourceFlowrate")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(23, 73, 231, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(23, 153, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_SourcePressure = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_SourcePressure.setGeometry(QtCore.QRect(90, 150, 121, 22))
        self.lineEdit_SourcePressure.setObjectName("lineEdit_SourcePressure")
        self.radioButton_ConstantPressureSource = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_ConstantPressureSource.setGeometry(QtCore.QRect(20, 120, 181, 20))
        self.radioButton_ConstantPressureSource.setObjectName("radioButton_ConstantPressureSource")
        self.radioButton_PumpSource = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_PumpSource.setGeometry(QtCore.QRect(20, 210, 181, 20))
        self.radioButton_PumpSource.setObjectName("radioButton_PumpSource")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 291, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(20, 39, 191, 16))
        self.label_3.setObjectName("label_3")
        self.Pump_Selection = QtWidgets.QComboBox(self.groupBox_4)
        self.Pump_Selection.setGeometry(QtCore.QRect(73, 33, 171, 31))
        self.Pump_Selection.setObjectName("Pump_Selection")
        self.pushButton_AnalyzeFlow = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_AnalyzeFlow.setGeometry(QtCore.QRect(90, 350, 151, 28))
        self.pushButton_AnalyzeFlow.setObjectName("pushButton_AnalyzeFlow")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 410, 291, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_Flowrate = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Flowrate.setGeometry(QtCore.QRect(90, 40, 111, 22))
        self.lineEdit_Flowrate.setObjectName("lineEdit_Flowrate")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(30, 43, 231, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_Pressure = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Pressure.setGeometry(QtCore.QRect(90, 88, 111, 22))
        self.lineEdit_Pressure.setText("")
        self.lineEdit_Pressure.setObjectName("lineEdit_Pressure")
        self.lineEdit_Head = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Head.setGeometry(QtCore.QRect(90, 137, 111, 22))
        self.lineEdit_Head.setText("")
        self.lineEdit_Head.setObjectName("lineEdit_Head")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(50, 140, 41, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_FluidPower = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_FluidPower.setGeometry(QtCore.QRect(100, 190, 101, 22))
        self.lineEdit_FluidPower.setText("")
        self.lineEdit_FluidPower.setObjectName("lineEdit_FluidPower")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(20, 193, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 220, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(210, 190, 71, 20))
        self.label_9.setObjectName("label_9")
        self.label_flowunit_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_flowunit_2.setGeometry(QtCore.QRect(208, 42, 51, 16))
        self.label_flowunit_2.setTextFormat(QtCore.Qt.RichText)
        self.label_flowunit_2.setObjectName("label_flowunit_2")
        self.label_pressunit_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_pressunit_2.setGeometry(QtCore.QRect(210, 90, 51, 20))
        self.label_pressunit_2.setTextFormat(QtCore.Qt.RichText)
        self.label_pressunit_2.setObjectName("label_pressunit_2")
        self.label_headunit = QtWidgets.QLabel(self.groupBox_5)
        self.label_headunit.setGeometry(QtCore.QRect(210, 140, 41, 16))
        self.label_headunit.setObjectName("label_headunit")
        self.label_4.raise_()
        self.lineEdit_Flowrate.raise_()
        self.label_5.raise_()
        self.lineEdit_Pressure.raise_()
        self.lineEdit_Head.raise_()
        self.label_6.raise_()
        self.lineEdit_FluidPower.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_flowunit_2.raise_()
        self.label_pressunit_2.raise_()
        self.label_headunit.raise_()
        self.label_flowunit = QtWidgets.QLabel(self.groupBox_3)
        self.label_flowunit.setGeometry(QtCore.QRect(220, 70, 121, 16))
        self.label_flowunit.setTextFormat(QtCore.Qt.RichText)
        self.label_flowunit.setObjectName("label_flowunit")
        self.label_pressunit = QtWidgets.QLabel(self.groupBox_3)
        self.label_pressunit.setGeometry(QtCore.QRect(220, 150, 51, 20))
        self.label_pressunit.setTextFormat(QtCore.Qt.RichText)
        self.label_pressunit.setObjectName("label_pressunit")
        self.radioButton_ConstantFlowrateSource.raise_()
        self.label.raise_()
        self.lineEdit_SourceFlowrate.raise_()
        self.label_2.raise_()
        self.lineEdit_SourcePressure.raise_()
        self.radioButton_ConstantPressureSource.raise_()
        self.radioButton_PumpSource.raise_()
        self.groupBox_4.raise_()
        self.pushButton_AnalyzeFlow.raise_()
        self.groupBox_5.raise_()
        self.label_flowunit.raise_()
        self.label_pressunit.raise_()
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(850, 15, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Save.setText(_translate("Dialog", "Save"))
        self.pushButton_SaveAs.setText(_translate("Dialog", "Save As"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_FlowReport), _translate("Dialog", "Flow Report"))
        self.label_20.setText(_translate("Dialog", "Zoom"))
        self.pushButton_RefreshSketch.setText(_translate("Dialog", "Refresh Sketch"))
        self.groupBox.setTitle(_translate("Dialog", "Show Pipe:"))
        self.checkBox_Length.setText(_translate("Dialog", "Length"))
        self.checkBox_DeltaP.setText(_translate("Dialog", "DeltaP"))
        self.checkBox_DeltaH.setText(_translate("Dialog", "DeltaH"))
        self.groupBox_2.setTitle(_translate("Dialog", "Show Node:"))
        self.checkBox_Zvalue.setText(_translate("Dialog", "z-value"))
        self.checkBox_Pressure.setText(_translate("Dialog", "pressure"))
        self.checkBox_Head.setText(_translate("Dialog", "head"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SystemSketch), _translate("Dialog", "System Sketch"))
        self.label_10.setText(_translate("Dialog", "Minimum Flow:                                  in^3/s"))
        self.label_11.setText(_translate("Dialog", "Maximum Flow:                                  in^3/s"))
        self.pushButton_GenerateCurves.setText(_translate("Dialog", "Generate Curves(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SystemCurve), _translate("Dialog", "System Curve"))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_GetFlowSystemFile.setText(_translate("Dialog", "Get Flow System File"))
        self.groupBox_3.setTitle(_translate("Dialog", "Flow Source"))
        self.radioButton_ConstantFlowrateSource.setText(_translate("Dialog", "Constant Flowrate Source"))
        self.lineEdit_SourceFlowrate.setText(_translate("Dialog", "20"))
        self.label.setText(_translate("Dialog", "Flowrate:"))
        self.label_2.setText(_translate("Dialog", "Pressure:"))
        self.lineEdit_SourcePressure.setText(_translate("Dialog", "10"))
        self.radioButton_ConstantPressureSource.setText(_translate("Dialog", "Constant Pressure Source"))
        self.radioButton_PumpSource.setText(_translate("Dialog", "Pump Source"))
        self.groupBox_4.setTitle(_translate("Dialog", "Pump Data"))
        self.label_3.setText(_translate("Dialog", "Pump:"))
        self.pushButton_AnalyzeFlow.setText(_translate("Dialog", "Analyze Flow"))
        self.groupBox_5.setTitle(_translate("Dialog", "Calculated Source Performance"))
        self.label_4.setText(_translate("Dialog", "Flowrate:"))
        self.label_5.setText(_translate("Dialog", "Pressure:"))
        self.label_6.setText(_translate("Dialog", "Head:"))
        self.label_7.setText(_translate("Dialog", "Fluid Power:"))
        self.label_8.setText(_translate("Dialog", "(Pressure * Flowrate)"))
        self.label_9.setText(_translate("Dialog", "lbf-in/s"))
        self.label_flowunit_2.setText(_translate("Dialog", "gpm"))
        self.label_pressunit_2.setText(_translate("Dialog", "psi"))
        self.label_headunit.setText(_translate("Dialog", "in"))
        self.label_flowunit.setText(_translate("Dialog", "gpm"))
        self.label_pressunit.setText(_translate("Dialog", "psi"))
        self.label_12.setText(_translate("Dialog", "Pipe Network Flow Analysis"))

